# Generated by Django 4.0.3 on 2022-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('pcount', models.IntegerField()),
                ('pdate', models.DateTimeField()),
                ('pmorev', models.BooleanField()),
            ],
        ),
    ]
