# Generated by Django 4.0.3 on 2022-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=10)),
                ('hname', models.TextField()),
                ('hcapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icode', models.CharField(max_length=10)),
                ('iname', models.TextField()),
                ('icount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=15)),
                ('sname', models.TextField()),
                ('sdob', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='papers',
            name='pdate',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='pmorev',
        ),
    ]
