# Generated by Django 4.0.3 on 2022-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0003_papers_department_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilator',
            name='idepartment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
