# Generated by Django 4.0.3 on 2022-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0004_invigilator_idepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(max_length=10)),
                ('eyear', models.IntegerField()),
                ('eprogram', models.TextField()),
                ('esemester', models.TextField()),
            ],
        ),
    ]
