# Generated by Django 4.0.3 on 2022-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0006_papers_eid_student_eid_student_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pid',
        ),
        migrations.AddField(
            model_name='student',
            name='pid0',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pid1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pid2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pid3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pid4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pid5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
