# Generated by Django 4.0.3 on 2022-03-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0007_remove_student_pid_student_pid0_student_pid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pid0',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pid1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pid2',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pid3',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pid4',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pid5',
            field=models.CharField(max_length=15),
        ),
    ]
