# Generated by Django 4.0.3 on 2022-03-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0011_alter_exam_ecode_alter_hall_hcode_alter_hall_hname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='etime',
            field=models.CharField(max_length=5),
        ),
    ]
