# Generated by Django 4.0.3 on 2022-03-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0012_alter_timetable_etime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='dornot',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
