# Generated by Django 4.0.3 on 2022-03-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0013_timetable_dornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='ptassigned',
            field=models.IntegerField(default=0),
        ),
    ]
