# Generated by Django 4.0.3 on 2022-03-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0014_papers_ptassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='ptassigned',
        ),
        migrations.AddField(
            model_name='papers',
            name='dornot',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
