# Generated by Django 4.0.3 on 2022-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0015_remove_papers_ptassigned_papers_dornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='eid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
