# Generated by Django 4.0.3 on 2022-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0018_invigilator_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
