# Generated by Django 4.0.3 on 2022-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0020_student_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='etime',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
