# Generated by Django 4.0.3 on 2022-03-21 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0021_papers_etime'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='edate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
