# Generated by Django 4.0.3 on 2022-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0023_alter_papers_edate_alter_papers_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scode',
            field=models.CharField(max_length=15),
        ),
    ]
