# Generated by Django 4.0.3 on 2022-03-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0024_alter_student_scode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='action',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
