# Generated by Django 4.0.3 on 2022-03-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0025_exam_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='check1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='check1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
