# Generated by Django 4.0.3 on 2022-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0026_papers_check1_student_check1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='check1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='check1',
        ),
        migrations.AddField(
            model_name='exam',
            name='papercheck',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='studentcheck',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
