# Generated by Django 4.0.3 on 2022-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0027_remove_papers_check1_remove_student_check1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echeck', models.IntegerField(default=0)),
            ],
        ),
    ]
