# Generated by Django 4.0.3 on 2022-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0035_alter_hall_eid_alter_invigilator_eid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='seated',
            field=models.IntegerField(default=-1),
        ),
    ]
