# Generated by Django 4.0.3 on 2022-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0036_student_seated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentstored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=-1)),
                ('eid', models.IntegerField(default=-1)),
                ('edate', models.DateField()),
                ('etime', models.CharField(max_length=5)),
                ('pid', models.IntegerField(default=-1)),
                ('seat', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='hid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat',
            field=models.IntegerField(default=-1),
        ),
    ]
