# Generated by Django 4.0.3 on 2022-04-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0039_sexambydate_sdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexambydate',
            name='eid',
            field=models.IntegerField(default=-1),
        ),
    ]
