# Generated by Django 4.0.3 on 2022-04-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0040_sexambydate_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallstorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatno', models.IntegerField(default=-1)),
                ('pid', models.IntegerField(default=-1)),
                ('scode', models.CharField(max_length=15)),
                ('edate', models.DateField()),
                ('etime', models.CharField(max_length=5)),
                ('eid', models.IntegerField(default=-1)),
                ('iname', models.TextField(default='UNASSIGNED')),
            ],
        ),
    ]
