# Generated by Django 4.0.3 on 2022-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0041_hallstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallstorage',
            name='hid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='hallstorage',
            name='sassigned',
            field=models.IntegerField(default=-1),
        ),
    ]
