# Generated by Django 4.0.3 on 2022-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0042_hallstorage_hid_hallstorage_sassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='view',
            field=models.CharField(default='disabled', max_length=8),
        ),
    ]
