# Generated by Django 4.0.3 on 2022-04-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0043_timetable_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='final',
            field=models.CharField(default='disabled', max_length=8),
        ),
        migrations.AddField(
            model_name='timetable',
            name='full',
            field=models.IntegerField(default=-1),
        ),
    ]
