# Generated by Django 4.0.3 on 2022-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0044_timetable_final_timetable_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='full',
            field=models.IntegerField(default=0),
        ),
    ]
