# Generated by Django 4.0.3 on 2022-04-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0046_hallstorage_icode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallstorage',
            old_name='icode',
            new_name='iid',
        ),
    ]
