# Generated by Django 4.0.3 on 2022-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0049_attendancestored'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestored',
            name='present',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancestored',
            name='scode',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
